version: "3.9"

services:
  web:
    build: .
    image: php:8.2-apache
    container_name: lamp-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - lamp-network

  phpunit:
    build: .
    image: php:8.2-apache
    container_name: lamp-tests
    volumes:
      - ./www:/var/www/html
    environment:
      - DB_DSN=mysql:host=db;dbname=test_db
      - DB_USER=root
      - DB_PASS=password
    depends_on:
      - db
    # This command runs tests and then stops the container
    entrypoint: ["/var/www/html/prod/vendor/bin/phpunit", "/var/www/html/tests"]
    networks:
      - lamp-network

  db:
    image: mysql:8.0
    container_name: lamp-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sql_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - lamp-network

networks:
  lamp-network:
    driver: bridge

volumes:
  db_data: