<?php
declare(strict_types=1);

namespace App\Repository;

use PDO;
use PharIo\Manifest\Email;
use App\Models\UserModel;
use function PHPUnit\Framework\returnArgument;
use App\Models\RoleEnum;

class UserRepository
{
    private PDO $pdo;

    public function __construct(PDO $pdo)
    {
        $this->pdo = $pdo;
    }

    /**
     * Finds a user and determines their role by checking specialized tables.
     */
    public function findById(string $hexId): ?UserModel
    {
        $sql = "SELECT 
                HEX(u.id) as id, u.email, u.password, u.first_name, u.last_name, u.is_active, u.created_at,
                s.cv_path, s.status, -- Added these fields from the student table
                CASE 
                    WHEN a.user_id IS NOT NULL THEN 'admin'
                    WHEN p.user_id IS NOT NULL THEN 'pilote'
                    WHEN s.user_id IS NOT NULL THEN 'student'
                    ELSE NULL
                END as role
            FROM user u
            LEFT JOIN administrator a ON u.id = a.user_id
            LEFT JOIN pilot p ON u.id = p.user_id
            LEFT JOIN student s ON u.id = s.user_id
            WHERE u.id = UNHEX(?)";

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute([$hexId]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);

        return $row ? UserModel::fromArray($row) : null;
    }



    public function findByEmail(string|Email $email): ?UserModel
    {
        // If it's an object, convert it to a string first
        $emailString = ($email instanceof Email) ? $email->asString() : $email;

        $sql = "SELECT 
                HEX(u.id) as id, u.email, u.password, u.first_name, u.last_name, u.is_active, u.created_at,
                CASE 
                    WHEN a.user_id IS NOT NULL THEN 'admin'
                    WHEN p.user_id IS NOT NULL THEN 'pilote'
                    WHEN s.user_id IS NOT NULL THEN 'student'
                    ELSE NULL
                END as role
            FROM user u
            LEFT JOIN administrator a ON u.id = a.user_id
            LEFT JOIN pilot p ON u.id = p.user_id
            LEFT JOIN student s ON u.id = s.user_id
            WHERE u.email = ?";

        $stmt = $this->pdo->prepare($sql);
        $stmt->execute([$emailString]);
        $row = $stmt->fetch(PDO::FETCH_ASSOC);

        return $row ? UserModel::fromArray($row) : null;
    }

    /**
     * Inserts a user. ID is generated by the MySQL trigger (UUIDv7).
     * Returns the Hex ID of the newly created user.
     */
    public function push(UserModel $user): ?string
    {
        try {
            $this->pdo->beginTransaction();

            // 1. Prepare and Execute User Insertion
            // Note: Using UUID_TO_BIN(UUID()) if you aren't providing a UUID from PHP
            $sql = "INSERT INTO user (id, email, password, first_name, last_name, is_active) 
                VALUES (UUID_TO_BIN(UUID()), :email, :password, :first_name, :last_name, :is_active)";

            $stmt = $this->pdo->prepare($sql);
            $stmt->execute([
                ':email' => $user->email->asString(),
                ':password' => $user->password, // Ensure this is hashed before calling push!
                ':first_name' => $user->first_name,
                ':last_name' => $user->last_name,
                ':is_active' => $user->is_active ? 1 : 0
            ]);

            // 2. Retrieve the Binary ID we just created
            $stmt = $this->pdo->prepare("SELECT id FROM user WHERE email = ?");
            $stmt->execute([$user->email->asString()]);
            $binaryId = $stmt->fetchColumn();

            if (!$binaryId) {
                throw new \Exception("Failed to retrieve created user ID.");
            }

            // 3. Handle Role Assignment
            // Students don't have a specific extra table based on your 'describe' results
            if ($user->role === RoleEnum::Admin) {
                $stmt = $this->pdo->prepare("INSERT INTO administrator (user_id) VALUES (?)");
                $stmt->execute([$binaryId]);
            } elseif ($user->role === RoleEnum::Pilote) {
                $stmt = $this->pdo->prepare("INSERT INTO pilot (user_id) VALUES (?)");
                $stmt->execute([$binaryId]);
            }

            $this->pdo->commit();
            return bin2hex($binaryId); // Return as hex string for the controller

        } catch (\Exception $e) {
            $this->pdo->rollBack();
            // Log $e->getMessage() here if needed
            return null;
        }
    }

    public function updateCvPath(string $hexUserId, string $path): bool
    {
        // This query handles both cases: 
        // 1. Student record doesn't exist yet -> Create it
        // 2. Student record exists -> Update cv_path
        $sql = "INSERT INTO student (user_id, cv_path) 
            VALUES (UNHEX(:id), :path)
            ON DUPLICATE KEY UPDATE cv_path = :path_update";

        $stmt = $this->pdo->prepare($sql);

        return $stmt->execute([
            'id' => $hexUserId,
            'path' => $path,
            'path_update' => $path
        ]);
    }

    public function makeStudent(string $userHexId, string $status = 'Searching'): bool
    {
        $stmt = $this->pdo->prepare("INSERT INTO student (user_id, status) VALUES (UNHEX(?), ?)");
        return $stmt->execute([$userHexId, $status]);
    }

    public function delete(string $hexId): bool
    {
        $stmt = $this->pdo->prepare("DELETE FROM user WHERE id = UNHEX(?)");
        return $stmt->execute([$hexId]);
    }
}