# site main
<VirtualHost *:80>
    ServerName prod.localhost
    DocumentRoot /var/www/html/prod
    ErrorLog ${APACHE_LOG_DIR}/prod_error.log
    CustomLog ${APACHE_LOG_DIR}/prod_access.log combined
</VirtualHost>

<VirtualHost *:8080>
    ServerName cdn.localhost
    DocumentRoot /var/www/html/cdn

    Header always set Access-Control-Allow-Origin "http://prod.localhost:8080"
    Header always set Access-Control-Allow-Methods "GET, OPTIONS"
    Header always set Access-Control-Allow-Headers "Content-Type"

    <Directory "/var/www/html/cdn">
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
